
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_


#ifndef WITH_SECURITY
#define WITH_SECURITY 0
#endif 


#define SICSLOWPAN_CONF_FRAG 0
#define UIP_CONF_BUFFER_SIZE 160

#undef TSCH_SCHEDULE_CONF_DEFAULT_LENGTH
#define TSCH_SCHEDULE_CONF_DEFAULT_LENGTH 32

#undef TSCH_CONF_DEFAULT_TIMESLOT_LENGTH
#define TSCH_CONF_DEFAULT_TIMESLOT_LENGTH 15000

#define ENERGEST_CONF_ON 1

#define TSCH_CONF_DEFAULT_HOPPING_SEQUENCE (uint8_t[]){17, 23, 15, 25, 19, 11, 13, 21}

#undef  ORCHESTRA_CONF_UNICAST_PERIOD 
#define ORCHESTRA_CONF_UNICAST_PERIOD   8

#undef ORCHESTRA_CONF_COMMON_SHARED_PERIOD 
#define ORCHESTRA_CONF_COMMON_SHARED_PERIOD 12

#undef ORCHESTRA_CONF_EBSF_PERIOD
#define ORCHESTRA_CONF_EBSF_PERIOD  34

#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0x81a5



#undef UIP_CONF_MAX_ROUTES
#define UIP_CONF_MAX_ROUTES 0
#undef RPL_CONF_MOP
#define RPL_CONF_MOP RPL_MOP_NON_STORING 
#undef ORCHESTRA_CONF_RULES
#define ORCHESTRA_CONF_RULES { &eb_per_time_source, &unicast_per_neighbor_rpl_ns, &default_common } 


#undef NETSTACK_CONF_MAC
#define NETSTACK_CONF_MAC     tschmac_driver
#undef NETSTACK_CONF_RDC
#define NETSTACK_CONF_RDC     nordc_driver
#undef NETSTACK_CONF_FRAMER
#define NETSTACK_CONF_FRAMER  framer_802154



#define RPL_CONF_DIO_INTERVAL_MIN 4



#define TSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL 0 
#define TSCH_CONF_WITH_LINK_SELECTOR 1 

#define TSCH_CALLBACK_NEW_TIME_SOURCE orchestra_callback_new_time_source
#define TSCH_CALLBACK_PACKET_READY orchestra_callback_packet_ready
#define NETSTACK_CONF_ROUTING_NEIGHBOR_ADDED_CALLBACK orchestra_callback_child_added
#define NETSTACK_CONF_ROUTING_NEIGHBOR_REMOVED_CALLBACK orchestra_callback_child_removed


#undef SYS_CTRL_CONF_OSC32K_USE_XTAL
#define SYS_CTRL_CONF_OSC32K_USE_XTAL 1


#undef DCOSYNCH_CONF_ENABLED
#define DCOSYNCH_CONF_ENABLED 0

#undef CC2420_CONF_SFD_TIMESTAMPS
#define CC2420_CONF_SFD_TIMESTAMPS 1


#undef TSCH_CONF_AUTOSTART
#define TSCH_CONF_AUTOSTART 0


#define TSCH_CONF_MAX_EB_PERIOD (2* CLOCK_SECOND)


 
#undef UIP_CONF_TCP
#define UIP_CONF_TCP 0
#undef QUEUEBUF_CONF_NUM
#define QUEUEBUF_CONF_NUM 4
#undef RPL_NS_CONF_LINK_NUM
#define RPL_NS_CONF_LINK_NUM  4
#undef NBR_TABLE_CONF_MAX_NEIGHBORS
#define NBR_TABLE_CONF_MAX_NEIGHBORS 5
#undef UIP_CONF_ND6_SEND_NS
#define UIP_CONF_ND6_SEND_NS 0
#undef SICSLOWPAN_CONF_FRAG
#define SICSLOWPAN_CONF_FRAG 0

#define DTSF_CONF_PACKET_GENERATION_RATE  2
  

#endif 