#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#ifndef WITH_SECURITY
#define WITH_SECURITY 0
#endif 

#define SICSLOWPAN_CONF_FRAG 0
#define UIP_CONF_BUFFER_SIZE 160


#define TSCH_CONF_WITH_SIXTOP 1

#define ENERGEST_CONF_ON 1

#define TSCH_CONF_DEFAULT_HOPPING_SEQUENCE (uint8_t[]){17, 23, 15, 25, 19, 11, 13, 21}


#define TSCH_SCHEDULE_CONF_DEFAULT_LENGTH 32


#undef TSCH_SCHEDULE_CONF_MAX_LINKS
#define TSCH_SCHEDULE_CONF_MAX_LINKS 32


#undef TSCH_CONF_MAX_EB_PERIOD 
#define TSCH_CONF_MAX_EB_PERIOD (2 * CLOCK_SECOND)


#define TSCH_CONF_DEFAULT_TIMESLOT_LENGTH 15000


#undef RPL_CONF_MOP
#define RPL_CONF_MOP RPL_MOP_NON_STORING 

#undef SYS_CTRL_CONF_OSC32K_USE_XTAL
#define SYS_CTRL_CONF_OSC32K_USE_XTAL 1


#undef DCOSYNCH_CONF_ENABLED
#define DCOSYNCH_CONF_ENABLED 0

#undef CC2420_CONF_SFD_TIMESTAMPS
#define CC2420_CONF_SFD_TIMESTAMPS 1


#define TSCH_CONF_AUTOSTART 0

#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0x81a5

#undef  MAC_CONF_WITH_TSCH
#define MAC_CONF_WITH_TSCH 1


#undef NETSTACK_CONF_MAC
#define NETSTACK_CONF_MAC     tschmac_driver

#undef NETSTACK_CONF_RDC
#define NETSTACK_CONF_RDC     nordc_driver

#undef NETSTACK_CONF_FRAMER
#define NETSTACK_CONF_FRAMER  framer_802154


#define RPL_CONF_DIO_INTERVAL_MIN 5




#undef TSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL
#define TSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL 1 


#undef UIP_CONF_TCP
#define UIP_CONF_TCP 0
#undef QUEUEBUF_CONF_NUM
#define QUEUEBUF_CONF_NUM 4
#undef RPL_NS_CONF_LINK_NUM
#define RPL_NS_CONF_LINK_NUM  4
#undef NBR_TABLE_CONF_MAX_NEIGHBORS
#define NBR_TABLE_CONF_MAX_NEIGHBORS 5
#undef UIP_CONF_ND6_SEND_NS
#define UIP_CONF_ND6_SEND_NS 0
#undef SICSLOWPAN_CONF_FRAG
#define SICSLOWPAN_CONF_FRAG 0

#undef DTSF_CONF_PACKET_GENERATION_RATE  
#define DTSF_CONF_PACKET_GENERATION_RATE  2



#endif
